/*
 * Chapter 2, The Workshop: levels 6-10. Teaches stairs, bridges, levers and ramps, then a
 * finale that combines stairs, a bridge, and a lever. Workbench pine, sawdust; tray adds
 * stairs, lever, marble, bridge, ramp and tallDomino as each level introduces them.
 */

import type { LevelDef } from '../types.ts'

export const WORKSHOP_LEVELS: LevelDef[] = [
  {
    id: 6,
    chapter: 'workshop',
    name: 'Step Down',
    hint: 'Stairs carry the chain down from the block to the bench top.',
    table: { width: 140, depth: 70 },
    fixtures: [
      { id: 'f-block', kind: 'block', x: -45, y: 0, z: 0, rotY: 0, locked: true },
      { id: 'f-trigger', kind: 'pendulum', x: -45, y: 6, z: 0, rotY: 0, locked: true },
      { id: 'f-goal', kind: 'bell', x: 51, y: 0, z: 8, rotY: 0, locked: true },
      { id: 'f-star', kind: 'star', x: 10, y: 0, z: 9.35, rotY: Math.PI / 2, locked: true },
    ],
    inventory: { domino: 26, stairs: 1 },
    parPieces: 20,
    camera: { target: [0, 3, 4], distance: 190, yaw: 0, pitch: 0.75 },
    solution: [
      { id: 's1', kind: 'stairs', x: -30, y: 0, z: 0, rotY: 0 },
      { id: 's2', kind: 'domino', x: -41.8, y: 0, z: 0, rotY: 0 },
      { id: 's3', kind: 'domino', x: -37, y: 0, z: 0, rotY: 0 },
      { id: 's4', kind: 'domino', x: -32.2, y: 0, z: 0, rotY: 0 },
      { id: 's5', kind: 'domino', x: -27.4, y: 0, z: 0, rotY: 0 },
      { id: 's6', kind: 'domino', x: -22.6, y: 0, z: 0, rotY: 0 },
      { id: 's7', kind: 'domino', x: -17.8, y: 0, z: 0, rotY: 0 },
      { id: 's8', kind: 'domino', x: -13, y: 0, z: 0, rotY: 0 },
      { id: 's9', kind: 'domino', x: -8.315, y: 0, z: 0.632, rotY: -0.359 },
      { id: 's10', kind: 'domino', x: -3.82, y: 0, z: 2.317, rotY: -0.359 },
      { id: 's11', kind: 'domino', x: 0.674, y: 0, z: 4.003, rotY: -0.359 },
      { id: 's12', kind: 'domino', x: 5.169, y: 0, z: 5.688, rotY: -0.359 },
      { id: 's13', kind: 'domino', x: 9.836, y: 0, z: 6.767, rotY: -0.197 },
      { id: 's14', kind: 'domino', x: 14.543, y: 0, z: 7.709, rotY: -0.197 },
      { id: 's15', kind: 'domino', x: 19.314, y: 0, z: 8, rotY: 0 },
      { id: 's16', kind: 'domino', x: 24.114, y: 0, z: 8, rotY: 0 },
      { id: 's17', kind: 'domino', x: 28.914, y: 0, z: 8, rotY: 0 },
      { id: 's18', kind: 'domino', x: 33.714, y: 0, z: 8, rotY: 0 },
      { id: 's19', kind: 'domino', x: 38.514, y: 0, z: 8, rotY: 0 },
    ],
  },
  {
    id: 7,
    chapter: 'workshop',
    name: 'Gap Crossing',
    hint: 'The bridge rests on both platforms. Lay it across before you chain over.',
    table: { width: 170, depth: 70 },
    fixtures: [
      { id: 'f-p1', kind: 'platform', x: -45, y: 0, z: 0, rotY: 0, locked: true },
      { id: 'f-trigger', kind: 'pendulum', x: -45, y: 10, z: 0, rotY: 0, locked: true },
      { id: 'f-p2', kind: 'platform', x: 7, y: 0, z: 0, rotY: 0, locked: true },
      { id: 'f-goal', kind: 'bell', x: 20, y: 10, z: 6, rotY: 0, locked: true },
      { id: 'f-star', kind: 'star', x: 13, y: 10, z: 8.5, rotY: Math.PI / 2, locked: true },
    ],
    inventory: { domino: 17, bridge: 1 },
    parPieces: 14,
    camera: { target: [-10, 5, 3], distance: 210, yaw: 0, pitch: 0.7 },
    solution: [
      { id: 's1', kind: 'bridge', x: -19, y: 0, z: 0, rotY: 0 },
      { id: 's2', kind: 'domino', x: -41.8, y: 0, z: 0, rotY: 0 },
      { id: 's3', kind: 'domino', x: -37, y: 0, z: 0, rotY: 0 },
      { id: 's4', kind: 'domino', x: -32.2, y: 0, z: 0, rotY: 0 },
      { id: 's5', kind: 'domino', x: -27.4, y: 0, z: 0, rotY: 0 },
      { id: 's6', kind: 'domino', x: -22.6, y: 0, z: 0, rotY: 0 },
      { id: 's7', kind: 'domino', x: -17.8, y: 0, z: 0, rotY: 0 },
      { id: 's8', kind: 'domino', x: -13, y: 0, z: 0, rotY: 0 },
      { id: 's9', kind: 'domino', x: -8.2, y: 0, z: 0, rotY: 0 },
      { id: 's10', kind: 'domino', x: -3.4, y: 0, z: 0, rotY: 0 },
      { id: 's11', kind: 'domino', x: 1.252, y: 0, z: 0.626, rotY: -0.464 },
      { id: 's12', kind: 'domino', x: 5.545, y: 0, z: 2.773, rotY: -0.464 },
      { id: 's13', kind: 'domino', x: 9.945, y: 0, z: 4.691, rotY: -0.405 },
    ],
  },
  {
    id: 8,
    chapter: 'workshop',
    name: 'Whip Around',
    hint: 'The falling domino tips the lever. Set the marble on the far end.',
    table: { width: 170, depth: 70 },
    fixtures: [
      { id: 'f-trigger', kind: 'pendulum', x: -70, y: 0, z: 0, rotY: 0, locked: true },
      { id: 'f-goal', kind: 'bell', x: 40, y: 0, z: 6, rotY: 0, locked: true },
      { id: 'f-star', kind: 'star', x: -19.6, y: 0, z: 6.5, rotY: Math.PI / 2, locked: true },
    ],
    inventory: { domino: 19, lever: 1, marble: 1 },
    parPieces: 16,
    camera: { target: [-5, 3, 4], distance: 210, yaw: 0, pitch: 0.7 },
    solution: [
      { id: 's1', kind: 'lever', x: 0, y: 0, z: 6, rotY: 0 },
      { id: 's2', kind: 'domino', x: -10, y: 0, z: 6, rotY: 0 },
      { id: 's3', kind: 'marble', x: 10, y: 0, z: 6, rotY: 0 },
      { id: 's4', kind: 'domino', x: -66.8, y: 0, z: 0, rotY: 0 },
      { id: 's5', kind: 'domino', x: -62, y: 0, z: 0, rotY: 0 },
      { id: 's6', kind: 'domino', x: -57.2, y: 0, z: 0, rotY: 0 },
      { id: 's7', kind: 'domino', x: -52.4, y: 0, z: 0, rotY: 0 },
      { id: 's8', kind: 'domino', x: -47.6, y: 0, z: 0, rotY: 0 },
      { id: 's9', kind: 'domino', x: -42.8, y: 0, z: 0, rotY: 0 },
      { id: 's10', kind: 'domino', x: -38, y: 0, z: 0, rotY: 0 },
      { id: 's11', kind: 'domino', x: -33.2, y: 0, z: 0, rotY: 0 },
      { id: 's12', kind: 'domino', x: -28.482, y: 0, z: 0.506, rotY: -0.322 },
      { id: 's13', kind: 'domino', x: -23.933, y: 0, z: 2.034, rotY: -0.464 },
      { id: 's14', kind: 'domino', x: -19.639, y: 0, z: 4.18, rotY: -0.464 },
      { id: 's15', kind: 'domino', x: -15.121, y: 0, z: 5.72, rotY: -0.245 },
    ],
  },
  {
    id: 9,
    chapter: 'workshop',
    name: 'Downhill Roll',
    hint: 'Knock the marble onto the ramp and let gravity carry it to the bell.',
    table: { width: 150, depth: 70 },
    fixtures: [
      { id: 'f-platform', kind: 'platform', x: -19, y: 0, z: 0, rotY: 0, locked: true },
      { id: 'f-trigger', kind: 'pendulum', x: -44, y: 10, z: 0, rotY: 0, locked: true },
      { id: 'f-goal', kind: 'bell', x: 35, y: 0, z: 0, rotY: 0, locked: true },
      { id: 'f-star', kind: 'star', x: -34, y: 10, z: 5.3, rotY: Math.PI / 2, locked: true },
    ],
    inventory: { domino: 10, tallDomino: 1, ramp: 1, marble: 1 },
    parPieces: 11,
    camera: { target: [-10, 3, 3], distance: 210, yaw: 0, pitch: 0.7 },
    solution: [
      { id: 's1', kind: 'ramp', x: 9, y: 0, z: 0, rotY: 0 },
      { id: 's2', kind: 'marble', x: -6, y: 0, z: 0, rotY: 0 },
      { id: 's3', kind: 'tallDomino', x: -8.32, y: 0, z: 0, rotY: 0 },
      { id: 's4', kind: 'domino', x: -40, y: 0, z: 0, rotY: -0.322 },
      { id: 's5', kind: 'domino', x: -35.446, y: 0, z: 1.518, rotY: -0.322 },
      { id: 's6', kind: 'domino', x: -30.893, y: 0, z: 0.964, rotY: 0.322 },
      { id: 's7', kind: 'domino', x: -26.249, y: 0, z: 0, rotY: 0 },
      { id: 's8', kind: 'domino', x: -21.449, y: 0, z: 0, rotY: 0 },
      { id: 's9', kind: 'domino', x: -16.649, y: 0, z: 0, rotY: 0 },
      { id: 's10', kind: 'domino', x: -11.849, y: 0, z: 0, rotY: 0 },
    ],
  },
  {
    id: 10,
    chapter: 'workshop',
    name: 'The Workshop Run',
    hint: 'Bridge the gap, take the stairs down, then whip the marble home.',
    table: { width: 240, depth: 70 },
    fixtures: [
      { id: 'f-block1', kind: 'block', x: -70, y: 0, z: 0, rotY: 0, locked: true },
      { id: 'f-trigger', kind: 'pendulum', x: -70, y: 6, z: 0, rotY: 0, locked: true },
      { id: 'f-block2', kind: 'block', x: -38, y: 0, z: 0, rotY: 0, locked: true },
      { id: 'f-goal', kind: 'bell', x: 84, y: 0, z: 6, rotY: 0, locked: true },
      { id: 'f-star', kind: 'star', x: 24, y: 0, z: 8.6, rotY: Math.PI / 2, locked: true },
    ],
    inventory: { domino: 31, bridge: 1, stairs: 1, lever: 1, marble: 1 },
    parPieces: 27,
    camera: { target: [0, 5, 3], distance: 320, yaw: 0, pitch: 0.65 },
    solution: [
      { id: 's1', kind: 'bridge', x: -52, y: 0, z: 0, rotY: 0 },
      { id: 's2', kind: 'stairs', x: -4, y: 0, z: 0, rotY: 0 },
      { id: 's3', kind: 'lever', x: 44, y: 0, z: 6, rotY: 0 },
      { id: 's4', kind: 'domino', x: 34, y: 0, z: 6, rotY: 0 },
      { id: 's5', kind: 'marble', x: 54, y: 0, z: 6, rotY: 0 },
      { id: 's6', kind: 'domino', x: -66.8, y: 0, z: 0, rotY: 0 },
      { id: 's7', kind: 'domino', x: -62, y: 0, z: 0, rotY: 0 },
      { id: 's8', kind: 'domino', x: -57.2, y: 0, z: 0, rotY: 0 },
      { id: 's9', kind: 'domino', x: -52.4, y: 0, z: 0, rotY: 0 },
      { id: 's10', kind: 'domino', x: -47.6, y: 0, z: 0, rotY: 0 },
      { id: 's11', kind: 'domino', x: -42.8, y: 0, z: 0, rotY: 0 },
      { id: 's12', kind: 'domino', x: -38, y: 0, z: 0, rotY: 0 },
      { id: 's13', kind: 'domino', x: -33.2, y: 0, z: 0, rotY: 0 },
      { id: 's14', kind: 'domino', x: -28.4, y: 0, z: 0, rotY: 0 },
      { id: 's15', kind: 'domino', x: -23.6, y: 0, z: 0, rotY: 0 },
      { id: 's16', kind: 'domino', x: -18.8, y: 0, z: 0, rotY: 0 },
      { id: 's17', kind: 'domino', x: -14, y: 0, z: 0, rotY: 0 },
      { id: 's18', kind: 'domino', x: -9.2, y: 0, z: 0, rotY: 0 },
      { id: 's19', kind: 'domino', x: -4.4, y: 0, z: 0, rotY: 0 },
      { id: 's20', kind: 'domino', x: 0.4, y: 0, z: 0, rotY: 0 },
      { id: 's21', kind: 'domino', x: 5.2, y: 0, z: 0, rotY: 0 },
      { id: 's22', kind: 'domino', x: 10.6, y: 0, z: 0, rotY: -0.507 },
      { id: 's23', kind: 'domino', x: 14.796, y: 0, z: 2.331, rotY: -0.507 },
      { id: 's24', kind: 'domino', x: 19.205, y: 0, z: 4.202, rotY: -0.359 },
      { id: 's25', kind: 'domino', x: 23.699, y: 0, z: 5.887, rotY: -0.359 },
      { id: 's26', kind: 'domino', x: 28.479, y: 0, z: 6, rotY: 0 },
    ],
  },
]
